# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templater.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Template_Gen(object):
    def setupUi(self, Template_Gen):
        Template_Gen.setObjectName("Template_Gen")
        Template_Gen.resize(627, 453)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/3d.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Template_Gen.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Template_Gen)
        self.widget.setGeometry(QtCore.QRect(9, 9, 302, 431))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.template_name_label = QtWidgets.QLabel(self.groupBox)
        self.template_name_label.setMinimumSize(QtCore.QSize(56, 0))
        self.template_name_label.setObjectName("template_name_label")
        self.horizontalLayout_4.addWidget(self.template_name_label)
        self.template_name_edit = QtWidgets.QLineEdit(self.groupBox)
        self.template_name_edit.setObjectName("template_name_edit")
        self.horizontalLayout_4.addWidget(self.template_name_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.template_path_label = QtWidgets.QLabel(self.groupBox)
        self.template_path_label.setMinimumSize(QtCore.QSize(56, 0))
        self.template_path_label.setObjectName("template_path_label")
        self.horizontalLayout_3.addWidget(self.template_path_label)
        self.template_path_edit = QtWidgets.QLineEdit(self.groupBox)
        self.template_path_edit.setObjectName("template_path_edit")
        self.horizontalLayout_3.addWidget(self.template_path_edit)
        self.template_path_button = QtWidgets.QPushButton(self.groupBox)
        self.template_path_button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.template_path_button.setText("")
        self.template_path_button.setObjectName("template_path_button")
        self.horizontalLayout_3.addWidget(self.template_path_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.widget1 = QtWidgets.QWidget(Template_Gen)
        self.widget1.setGeometry(QtCore.QRect(317, 9, 302, 431))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tags_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.tags_table.setObjectName("tags_table")
        self.tags_table.setColumnCount(0)
        self.tags_table.setRowCount(0)
        self.gridLayout_2.addWidget(self.tags_table, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_4)

        self.retranslateUi(Template_Gen)
        QtCore.QMetaObject.connectSlotsByName(Template_Gen)

    def retranslateUi(self, Template_Gen):
        _translate = QtCore.QCoreApplication.translate
        Template_Gen.setWindowTitle(_translate("Template_Gen", "Templater"))
        self.groupBox.setTitle(_translate("Template_Gen", "Common"))
        self.template_name_label.setText(_translate("Template_Gen", "Название\n"
"шаблона"))
        self.template_path_label.setText(_translate("Template_Gen", "Путь к XML \n"
"шаблону"))
        self.groupBox_3.setTitle(_translate("Template_Gen", "Faults"))
        self.groupBox_2.setTitle(_translate("Template_Gen", "Tags"))
        self.groupBox_4.setTitle(_translate("Template_Gen", "Networks"))

